const vehicles = {
  hilux:{brand:'Toyota',name:'Hilux',description:'Pickup reconocida por su resistencia, confiabilidad y capacidad todoterreno.',image:'toyota/toyota.jpg',price:'$37,700',specs:[['Precio','$37,700'],['Tracción','4×4 con modos de terreno'],['Capacidad','Hasta 1 tonelada'],['Carácter','Robusto y confiable']],metrics:[['Potencia',92],['Capacidad 4×4',96],['Tecnología',82],['Carga',94],['Diseño',88],['Confort',84]]},
  frontier:{brand:'Nissan',name:'Frontier',description:'Pickup moderna que combina fuerza, tecnología y comodidad en cada trayecto.',image:'https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=1200&q=85',specs:[['Tracción','4×4 inteligente'],['Tecnología','Asistencias avanzadas'],['Carácter','Deportivo y versátil']],metrics:[['Potencia',89],['Capacidad 4×4',91],['Tecnología',94],['Carga',88],['Diseño',92],['Confort',91]]},
  l200:{brand:'Mitsubishi',name:'L200',description:'Pickup preparada para terrenos exigentes y aventuras que piden máxima capacidad.',image:'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=85',specs:[['Tracción','Super Select 4WD'],['Suspensión','Reforzada'],['Carácter','Ágil y aventurero']],metrics:[['Potencia',86],['Capacidad 4×4',94],['Tecnología',86],['Carga',90],['Diseño',89],['Confort',87]]}
};
const galleryImages = [...document.querySelectorAll('.gallery-item img')].map(img=>({src:img.src,alt:img.alt}));
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];

function addRipple(event){const button=event.currentTarget; button.classList.remove('ripple'); void button.offsetWidth; button.classList.add('ripple')}
$$('.btn').forEach(b=>b.addEventListener('click',addRipple));

const menu=$('.menu-toggle'), nav=$('nav'); menu.addEventListener('click',()=>{const open=menu.classList.toggle('open');nav.classList.toggle('open',open);menu.setAttribute('aria-expanded',open);});
$$('nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.classList.remove('open');menu.setAttribute('aria-expanded','false')}));

const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(e=>revealObserver.observe(e));

let lastScrollPosition=0,scrollFrame;function updateScroll(){const top=window.scrollY, height=document.documentElement.scrollHeight-innerHeight,header=$('.site-header');$('.scroll-progress').style.width=`${top/height*100}%`;$('.back-top').classList.toggle('show',top>500);header.classList.toggle('scrolled',top>32);header.classList.toggle('header-hidden',top>140&&top>lastScrollPosition);lastScrollPosition=top;let current='inicio';$$('main section').forEach(s=>{if(top>=s.offsetTop-130)current=s.id});$$('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current));}window.addEventListener('scroll',()=>{if(!scrollFrame)scrollFrame=requestAnimationFrame(()=>{updateScroll();scrollFrame=null})},{passive:true});updateScroll();$('.back-top').addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));

$$('.filter').forEach(button=>button.addEventListener('click',()=>{const filter=button.dataset.filter;$$('.filter').forEach(b=>b.classList.toggle('active',b===button));$$('.vehicle-card').forEach(card=>{const show=filter==='all'||card.dataset.brand===filter;card.classList.toggle('hidden-card',!show);if(show){card.style.animation='none';void card.offsetWidth;card.style.animation='drop .45s ease both'}});document.querySelector('#vehiculos').scrollIntoView({behavior:'smooth',block:'start'});}));

const modal=$('#vehicle-modal');function openModal(key){const v=vehicles[key];$('#modal-image').src=v.image;$('#modal-image').alt=`${v.brand} ${v.name}`;$('#modal-brand').textContent=v.brand;$('#modal-title').textContent=v.name;$('#modal-copy').textContent=v.description;$('#modal-specs').innerHTML=v.specs.map(s=>`<div><span>${s[0]}</span><br>${s[1]}</div>`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';}$$('.details-btn').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openModal(b.dataset.vehicle)}));$$('.vehicle-card').forEach(c=>{c.addEventListener('click',()=>openModal(c.dataset.model));c.addEventListener('keydown',e=>{if(e.key==='Enter')openModal(c.dataset.model)})});$$('.modal-close,.modal-close-action').forEach(b=>b.addEventListener('click',closeModal));modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
$$('.card-content a').forEach(link=>link.addEventListener('click',event=>event.stopPropagation()));

function setComparison(key){const v=vehicles[key];$('#compare-brand').textContent=v.brand;$('#compare-model').textContent=v.name;$('#compare-description').textContent=v.description;$('.compare-model .details-btn').dataset.vehicle=key;$('#metrics').innerHTML=v.metrics.map(m=>`<div class="metric"><span>${m[0]}</span><div class="bar"><i style="width:${m[1]}%"></i></div><b>${m[1]}</b></div>`).join('');}setComparison('hilux');$$('.compare-tab').forEach(tab=>tab.addEventListener('click',()=>{ $$('.compare-tab').forEach(t=>t.classList.toggle('active',t===tab));setComparison(tab.dataset.compare)}));

let imageIndex=0;const lightbox=$('.lightbox');function showImage(index){imageIndex=(index+galleryImages.length)%galleryImages.length;const image=galleryImages[imageIndex];$('.lightbox img').src=image.src;$('.lightbox img').alt=image.alt;$('.lightbox p').textContent=`${imageIndex+1} / ${galleryImages.length}`;}$$('.gallery-item').forEach(item=>item.addEventListener('click',()=>{showImage(+item.dataset.image);lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}));function closeLightbox(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');document.body.style.overflow='';}$('.lightbox-close').addEventListener('click',closeLightbox);$('.previous').addEventListener('click',()=>showImage(imageIndex-1));$('.next').addEventListener('click',()=>showImage(imageIndex+1));lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});

$('.contact-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget,status=$('.form-status');if(!form.checkValidity()){status.textContent='Por favor, completa todos los campos correctamente.';form.reportValidity();return}status.textContent='¡Mensaje enviado! Pronto nos pondremos en contacto contigo.';form.reset();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeLightbox()}if(lightbox.classList.contains('open')&&e.key==='ArrowRight')showImage(imageIndex+1);if(lightbox.classList.contains('open')&&e.key==='ArrowLeft')showImage(imageIndex-1)});

const countObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;$$('[data-count]').forEach(el=>{const target=+el.dataset.count,duration=1100,start=performance.now();function tick(now){const progress=Math.min((now-start)/duration,1);el.textContent=Math.floor(target*progress)+(target===100?'%':'');if(progress<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)});countObserver.disconnect()}),{threshold:.5});countObserver.observe($('.numbers'));
